//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.530
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visao.ServicoReserva {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicoReserva.IServicoReserva")]
    public interface IServicoReserva {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoReserva/ObterCategoriasDeQuarto", ReplyAction="http://tempuri.org/IServicoReserva/ObterCategoriasDeQuartoResponse")]
        Modelo.Dominio.CategoriaDeQuarto[] ObterCategoriasDeQuarto();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoReserva/ConsultarDisponibilidade", ReplyAction="http://tempuri.org/IServicoReserva/ConsultarDisponibilidadeResponse")]
        bool ConsultarDisponibilidade(System.DateTime dataInicio, System.DateTime dataFim, long idCategoriaDeQuarto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoReserva/ReservarQuarto", ReplyAction="http://tempuri.org/IServicoReserva/ReservarQuartoResponse")]
        long ReservarQuarto(System.DateTime dataInicio, System.DateTime dataFim, long idCategoriaDeQuarto, long idCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoReserva/ConsultarReservas", ReplyAction="http://tempuri.org/IServicoReserva/ConsultarReservasResponse")]
        Modelo.Dominio.Reserva[] ConsultarReservas(long idCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoReserva/ObterReservas", ReplyAction="http://tempuri.org/IServicoReserva/ObterReservasResponse")]
        Modelo.Dominio.Reserva[] ObterReservas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoReserva/ObterReservasParaCheckin", ReplyAction="http://tempuri.org/IServicoReserva/ObterReservasParaCheckinResponse")]
        Modelo.Dominio.Reserva[] ObterReservasParaCheckin();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoReserva/ObterReserva", ReplyAction="http://tempuri.org/IServicoReserva/ObterReservaResponse")]
        Modelo.Dominio.Reserva ObterReserva(long idReserva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoReserva/CancelarReserva", ReplyAction="http://tempuri.org/IServicoReserva/CancelarReservaResponse")]
        void CancelarReserva(long idReserva);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicoReservaChannel : Visao.ServicoReserva.IServicoReserva, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicoReservaClient : System.ServiceModel.ClientBase<Visao.ServicoReserva.IServicoReserva>, Visao.ServicoReserva.IServicoReserva {
        
        public ServicoReservaClient() {
        }
        
        public ServicoReservaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicoReservaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoReservaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoReservaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Modelo.Dominio.CategoriaDeQuarto[] ObterCategoriasDeQuarto() {
            return base.Channel.ObterCategoriasDeQuarto();
        }
        
        public bool ConsultarDisponibilidade(System.DateTime dataInicio, System.DateTime dataFim, long idCategoriaDeQuarto) {
            return base.Channel.ConsultarDisponibilidade(dataInicio, dataFim, idCategoriaDeQuarto);
        }
        
        public long ReservarQuarto(System.DateTime dataInicio, System.DateTime dataFim, long idCategoriaDeQuarto, long idCliente) {
            return base.Channel.ReservarQuarto(dataInicio, dataFim, idCategoriaDeQuarto, idCliente);
        }
        
        public Modelo.Dominio.Reserva[] ConsultarReservas(long idCliente) {
            return base.Channel.ConsultarReservas(idCliente);
        }
        
        public Modelo.Dominio.Reserva[] ObterReservas() {
            return base.Channel.ObterReservas();
        }
        
        public Modelo.Dominio.Reserva[] ObterReservasParaCheckin() {
            return base.Channel.ObterReservasParaCheckin();
        }
        
        public Modelo.Dominio.Reserva ObterReserva(long idReserva) {
            return base.Channel.ObterReserva(idReserva);
        }
        
        public void CancelarReserva(long idReserva) {
            base.Channel.CancelarReserva(idReserva);
        }
    }
}
