//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.530
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visao.ServicoCliente {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicoCliente.IServicoCliente")]
    public interface IServicoCliente {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoCliente/CadastrarCliente", ReplyAction="http://tempuri.org/IServicoCliente/CadastrarClienteResponse")]
        void CadastrarCliente(Modelo.Dominio.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoCliente/AlterarCliente", ReplyAction="http://tempuri.org/IServicoCliente/AlterarClienteResponse")]
        void AlterarCliente(Modelo.Dominio.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoCliente/ExcluirCliente", ReplyAction="http://tempuri.org/IServicoCliente/ExcluirClienteResponse")]
        void ExcluirCliente(Modelo.Dominio.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoCliente/ObterClientes", ReplyAction="http://tempuri.org/IServicoCliente/ObterClientesResponse")]
        Modelo.Dominio.Cliente[] ObterClientes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoCliente/ObterCliente", ReplyAction="http://tempuri.org/IServicoCliente/ObterClienteResponse")]
        Modelo.Dominio.Cliente ObterCliente(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoCliente/BuscarCliente", ReplyAction="http://tempuri.org/IServicoCliente/BuscarClienteResponse")]
        Modelo.Dominio.Cliente BuscarCliente(string cpf);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicoClienteChannel : Visao.ServicoCliente.IServicoCliente, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicoClienteClient : System.ServiceModel.ClientBase<Visao.ServicoCliente.IServicoCliente>, Visao.ServicoCliente.IServicoCliente {
        
        public ServicoClienteClient() {
        }
        
        public ServicoClienteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicoClienteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoClienteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoClienteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void CadastrarCliente(Modelo.Dominio.Cliente cliente) {
            base.Channel.CadastrarCliente(cliente);
        }
        
        public void AlterarCliente(Modelo.Dominio.Cliente cliente) {
            base.Channel.AlterarCliente(cliente);
        }
        
        public void ExcluirCliente(Modelo.Dominio.Cliente cliente) {
            base.Channel.ExcluirCliente(cliente);
        }
        
        public Modelo.Dominio.Cliente[] ObterClientes() {
            return base.Channel.ObterClientes();
        }
        
        public Modelo.Dominio.Cliente ObterCliente(long id) {
            return base.Channel.ObterCliente(id);
        }
        
        public Modelo.Dominio.Cliente BuscarCliente(string cpf) {
            return base.Channel.BuscarCliente(cpf);
        }
    }
}
