//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.530
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visao.ServicoOcupacao {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicoOcupacao.IServicoOcupacao")]
    public interface IServicoOcupacao {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoOcupacao/RegistrarCheckin", ReplyAction="http://tempuri.org/IServicoOcupacao/RegistrarCheckinResponse")]
        Modelo.Dominio.Ocupacao RegistrarCheckin(long idReserva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoOcupacao/RegistrarCheckout", ReplyAction="http://tempuri.org/IServicoOcupacao/RegistrarCheckoutResponse")]
        Modelo.Dominio.Ocupacao RegistrarCheckout(long idQuarto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoOcupacao/PagarConta", ReplyAction="http://tempuri.org/IServicoOcupacao/PagarContaResponse")]
        void PagarConta(Modelo.Dominio.Conta conta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoOcupacao/RegistrarTerminoDeLimpeza", ReplyAction="http://tempuri.org/IServicoOcupacao/RegistrarTerminoDeLimpezaResponse")]
        void RegistrarTerminoDeLimpeza(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoOcupacao/ObterQuartosOcupados", ReplyAction="http://tempuri.org/IServicoOcupacao/ObterQuartosOcupadosResponse")]
        Modelo.Dominio.Quarto[] ObterQuartosOcupados();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicoOcupacaoChannel : Visao.ServicoOcupacao.IServicoOcupacao, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicoOcupacaoClient : System.ServiceModel.ClientBase<Visao.ServicoOcupacao.IServicoOcupacao>, Visao.ServicoOcupacao.IServicoOcupacao {
        
        public ServicoOcupacaoClient() {
        }
        
        public ServicoOcupacaoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicoOcupacaoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoOcupacaoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoOcupacaoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Modelo.Dominio.Ocupacao RegistrarCheckin(long idReserva) {
            return base.Channel.RegistrarCheckin(idReserva);
        }
        
        public Modelo.Dominio.Ocupacao RegistrarCheckout(long idQuarto) {
            return base.Channel.RegistrarCheckout(idQuarto);
        }
        
        public void PagarConta(Modelo.Dominio.Conta conta) {
            base.Channel.PagarConta(conta);
        }
        
        public void RegistrarTerminoDeLimpeza(long id) {
            base.Channel.RegistrarTerminoDeLimpeza(id);
        }
        
        public Modelo.Dominio.Quarto[] ObterQuartosOcupados() {
            return base.Channel.ObterQuartosOcupados();
        }
    }
}
